### ISSUE TITLE
find pattern evalutes to false always

### ISSUE THREAD

**Issue by plum** [vvl-rulez/btrfs-autosnap#1]
Thanks for excellent tool.
I have began to use it. Snapshot created without problem, however when using 'btrfs-autosnap -l ' get the following error:

`find: warning: ‘-name’ matches against basenames only, but the given pattern contains a directory separator (‘/’), thus the expression will evaluate to false all the time.  Did you mean ‘-wholename’?`

My root volume is  '_active/rootvol' mounted at    /

The created snapshot is clearly to be seen as '_active/rootvol-id7i6t'  with btrfs subvol list.

Any ideas?

**Comment by vaminakov** [comment]
Hello! Seems it's really problem of separator. I'll think how to solve it

**Comment by plum** [comment]
Very much Appreciated.   It's an ideal hook.

**Comment by plum** [comment]
I suspect this is happening due to the layout of my btrfs subvolumes.
The snapshots taken by btrfs-autosnap of root subvolume  (_active/rootvol) are being stored on subvol=256 whose label is '_active', and which is not mounted.
I can manually mount   subvol=_active to see if I get the same error. I'll report back.


EDIT:
Answer, No,  the command  $ btrfs-autosnap -l    does not find the snapshots, also when subvol-_active (subvolid=256)  is mounted in /var/lib/btrfs

**Comment by vaminakov** [comment]
Sure the problem is the layout of your btrfs subvolumes. When I created the utility, I did not expect that it is possible to use the root btrfs subvolume nested in another one (you have _active/rootvol), but just rootvol is expected.
Moreover, the snapshot is created correctly, but not only the list function (-l), but also the function of deleting old snapshots (-r) does not work. I don't see a quick fix without changing the functions.

**Comment by plum** [comment]
OK vvl-R, thanks for confirmation.
I said it was a good tool, so aiming to use it I'll do this: 
 I'll modify, with no downside whatsoever,  my btrfs nested _active/rootvol layout by snapshotting that subvol  to  a flat layout at _rootvol  (and  necessarily making necessary changes to fstab, my systemd boot loader, plus re-generating  initramfs).  

I think that should work.  No doubt the easiest solution, not so hard.

Kind regards,
John

**Comment by plum** [comment]
I have done the modification to my btrfs filesystem as proposed, except upon re-consideration of systemd-boot config, I did not re-generate an initramfs,
All has worked smoothly. I installed btrfs-autosnap, updated software with pacman and the hook both created and listed a snapshot.
Voila!

Now,  I only have to delete the original _active/subvolume. (scarey, eh?)

Thanks for kind advice.
John
